[workspace]
resolver = "2"

members = ["crates/extension_api"]
default-members = ["crates/extension_api"]

[workspace.package]
edition = "2024"
publish = false

[workspace.profile.release]
lto = false
opt-level = "s"
